apiVersion: secrets-store.csi.x-k8s.io/v1
kind: SecretProviderClass
metadata:
  name: {{ .Release.Name }}-secrets-provider
  namespace: {{ .Release.Namespace | default "training-portal" }}
spec:
  provider: azure
  secretObjects:
    - secretName: {{ .Values.secretName }}
      type: Opaque
      data:
        - objectName: user-portal-client-id
          key: AUDIENCE
  parameters:
    usePodIdentity: "false"
    useVMManagedIdentity: "false"
    useWorkloadIdentity: "true"
    keyvaultName: "{{ .Values.keyvaultName }}"
    tenantId: "{{ .Values.tenantId }}"
    clientID: "{{ .Values.workloadIdentity.clientId }}"
    objects: |
      array:
        - |
          objectName: user-portal-client-id
          objectType: secret
