apiVersion: secrets-store.csi.x-k8s.io/v1
kind: SecretProviderClass
metadata:
  name: {{ .Release.Name }}-secrets-provider
  namespace: {{ .Release.Namespace | default "training-portal" }}
spec:
  provider: azure
  secretObjects:
    - secretName: {{ .Values.secretName }}
      type: Opaque
      data:
        - objectName: pg-connection-string
          key: PG_CONNECTION_STRING
        - objectName: workload-client-id
          key: AZURE_CLIENT_ID
  parameters:
    usePodIdentity: "false"
    useVMManagedIdentity: "true"
    keyvaultName: "{{ .Values.keyvaultName }}"
    tenantId: "{{ .Values.tenantId }}"
    objects: |
      array:
        - |
          objectName: pg-connection-string
          objectType: secret
        - |
          objectName: workload-client-id
          objectType: secret
