apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ .Values.serviceAccount.name }}
  namespace: {{ .Release.Namespace | default "training-portal" }}
  labels:
    app.kubernetes.io/name: {{ .Values.serviceAccount.name }}
    app.kubernetes.io/part-of: training-portal
  annotations:
    azure.workload.identity/client-id: "{{ .Values.workloadIdentity.clientId }}"
